# Generated by Django 5.1.1 on 2024-09-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crear_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('grupo', models.CharField(choices=[('Orgánicos', 'Orgánicos'), ('Granulados', 'Granulados'), ('Líquidos', 'Líquidos'), ('Polvo', 'Polvo'), ('Materia Prima', 'Materia Prima'), ('Insumos', 'Insumos')], max_length=100)),
                ('unidad', models.CharField(choices=[('KL', 'Kilo'), ('KG', 'Kilogramos'), ('Litro', 'Litro'), ('GL', 'Galones'), ('MIL', 'Milímetros'), ('C.C', 'Centímetros Cúbicos')], max_length=100)),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
    ]
