# Generated by Django 5.1.1 on 2024-09-08 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('destinatario', models.CharField(max_length=100)),
                ('retira', models.CharField(max_length=100)),
                ('nota', models.TextField(blank=True, null=True)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_PM.crear_producto')),
            ],
        ),
    ]
