# Generated by Django 5.1.1 on 2024-09-08 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0002_entradaproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntradaProducto',
        ),
    ]
