# Generated by Django 5.1.1 on 2024-09-08 00:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0003_delete_entradaproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaEliminada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entrada', models.CharField(max_length=15, unique=True)),
                ('eliminado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('destinatario', models.CharField(max_length=100)),
                ('retiro', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_entrada', models.CharField(editable=False, max_length=15, unique=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_PM.crear_producto')),
            ],
        ),
    ]
