# Generated by Django 5.1.1 on 2024-10-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0005_remove_entradaproducto_destinatario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntradaEliminada',
        ),
        migrations.DeleteModel(
            name='EntradaProducto',
        ),
    ]
