# Generated by Django 5.1.1 on 2024-11-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0010_notaentrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('NIT', 'Nit'), ('CED', 'Cédula de ciudadanía'), ('NUI', 'Número único de identificación personal'), ('CED_EXT', 'Cédula de extranjero'), ('TI', 'Tarjeta de identidad')], max_length=10)),
                ('identificacion', models.CharField(max_length=20)),
                ('tipo_persona', models.CharField(choices=[('PJ', 'Razón social/persona jurídica'), ('PN', 'Persona natural')], max_length=2)),
                ('nombre', models.CharField(max_length=100)),
                ('primer_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('contacto_responsable', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono1', models.CharField(max_length=15)),
                ('telefono2', models.CharField(blank=True, max_length=15, null=True)),
                ('sexo', models.CharField(choices=[('EMP', 'Empresa'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=3)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('declarante_renta', models.BooleanField()),
                ('agente_renta', models.BooleanField()),
                ('autoretenedor', models.BooleanField()),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
        ),
    ]
