# Generated by Django 5.1.1 on 2024-11-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0011_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaentrada',
            name='cliente',
            field=models.CharField(default='PROECOLOGICOS S.A.S', max_length=100),
        ),
    ]
