# Generated by Django 5.1.1 on 2024-11-13 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0012_notaentrada_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notaentrada',
            old_name='cliente',
            new_name='cliente_nit',
        ),
    ]
