# Generated by Django 5.1.1 on 2024-11-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0013_rename_cliente_notaentrada_cliente_nit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notaentrada',
            name='cliente_nit',
        ),
    ]
