# Generated by Django 5.1.1 on 2024-11-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0014_remove_notaentrada_cliente_nit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
