# Generated by Django 5.1.1 on 2024-11-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0015_delete_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notaentrada',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='notaentrada',
            name='cliente',
            field=models.CharField(default='Proecologicos S.A.S', max_length=100),
        ),
    ]
