# Generated by Django 5.1.1 on 2024-11-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0016_remove_notaentrada_observaciones_notaentrada_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='crear_producto',
            name='linea',
            field=models.CharField(choices=[('insecticidas', 'Insecticidas'), ('fertilizantes', 'Fertilizantes'), ('materia prima', 'Materia Prima'), ('insumos', 'Insumos'), ('coayudantes', 'Coayudantes'), ('gravados', 'Gravados'), ('bioinsumos', 'Bioinsumos'), ('fungicidas', 'Fungicidas'), ('maquila', 'Maquila'), ('herbicidas', 'Herbicidas')], default='insecticidas', max_length=100),
        ),
    ]
