# Generated by Django 5.1 on 2024-11-14 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0018_alter_crear_producto_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='crear_producto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='crear_producto',
            name='linea',
            field=models.CharField(choices=[('Insecticidas', 'Insecticidas'), ('Fertilizantes', 'Fertilizantes'), ('Materia Prima', 'Materia Prima'), ('Insumos', 'Insumos'), ('Coayudantes', 'Coayudantes'), ('Gravados', 'Gravados'), ('Bioinsumos', 'Bioinsumos'), ('Fungicidas', 'Fungicidas'), ('Maquila', 'Maquila'), ('Herbicidas', 'Herbicidas')], max_length=100),
        ),
    ]
