# Generated by Django 5.1 on 2024-11-14 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0019_crear_producto_fecha_alter_crear_producto_linea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crear_producto',
            name='fecha',
        ),
        migrations.AddField(
            model_name='notaentrada',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='crear_producto',
            name='linea',
            field=models.CharField(choices=[('insecticidas', 'Insecticidas'), ('fertilizantes', 'Fertilizantes'), ('materia prima', 'Materia Prima'), ('insumos', 'Insumos'), ('coayudantes', 'Coayudantes'), ('gravados', 'Gravados'), ('bioinsumos', 'Bioinsumos'), ('fungicidas', 'Fungicidas'), ('maquila', 'Maquila'), ('herbicidas', 'Herbicidas')], max_length=100),
        ),
    ]
