# Generated by Django 5.1 on 2024-11-14 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0020_remove_crear_producto_fecha_notaentrada_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaentrada',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
