# Generated by Django 5.1 on 2024-11-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0021_alter_notaentrada_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notaentrada',
            name='fecha',
        ),
        migrations.AddField(
            model_name='notaentrada',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
