# Generated by Django 5.1.3 on 2024-11-22 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0022_remove_notaentrada_fecha_notaentrada_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crear_producto',
            name='unidad',
        ),
    ]
