# Generated by Django 5.1.3 on 2024-11-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0023_remove_crear_producto_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crear_producto',
            name='grupo',
            field=models.CharField(choices=[('001', 'Bifungicidas'), ('002', 'Comercializacion de productos'), ('003', 'Materia Prima'), ('004', 'Fertilizantes'), ('005', 'Foliares'), ('006', 'Granulados'), ('007', 'Insumos'), ('008', 'Líquido'), ('009', 'Organicos'), ('010', 'Polvo'), ('011', 'Productos fabricados - No Propios'), ('012', 'Pulverizador Liquido')], max_length=100),
        ),
        migrations.AlterField(
            model_name='crear_producto',
            name='linea',
            field=models.CharField(choices=[('001', 'Fertilizantes'), ('002', 'Bioinsumos'), ('003', 'Materia Prima'), ('004', 'Coayudantes'), ('005', 'Comercializacion de productos'), ('006', 'Equipos de pulverizador'), ('007', 'Fungicidas'), ('008', 'Herbicidas'), ('009', 'Insecticidas'), ('010', 'Insumos'), ('011', 'Mercancia en Consignacion'), ('012', 'Productos fabricados - No Propios')], max_length=100),
        ),
    ]
