# Generated by Django 5.1.3 on 2024-11-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0024_alter_crear_producto_grupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertarProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='uploads/', verbose_name='Archivo Excel')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False, verbose_name='¿Procesado?')),
            ],
        ),
    ]
