# Generated by Django 5.1.3 on 2024-11-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0025_insertarproductos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crear_producto',
            name='grupo',
            field=models.CharField(choices=[('001', 'Biofungicidas'), ('002', 'Comercializacion de productos'), ('003', 'Materia Prima'), ('004', 'Fertilizantes'), ('005', 'Foliares'), ('006', 'Granulados'), ('007', 'Insumos'), ('008', 'Líquido'), ('009', 'Organicos'), ('010', 'Polvo'), ('011', 'Productos fabricados - No Propios'), ('012', 'Pulverizador Liquido')], max_length=100),
        ),
    ]
