# Generated by Django 5.1.3 on 2024-11-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0028_remove_notaentrada_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaentrada',
            name='lote',
            field=models.CharField(default='', max_length=100),
        ),
    ]
