# Generated by Django 5.1.3 on 2024-12-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0029_alter_notaentrada_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nit', models.CharField(max_length=15, unique=True, verbose_name='NIT')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=15, verbose_name='Número Telefónico')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
            ],
        ),
    ]
