# Generated by Django 5.1.3 on 2024-12-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0030_crearproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearproveedor',
            name='id_proveedor',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
