# Generated by Django 5.1.3 on 2024-12-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PM', '0031_crearproveedor_id_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notaentrada',
            name='cliente',
        ),
        migrations.AddField(
            model_name='notaentrada',
            name='proveedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
